env: 
  API_VERSION: "googleapi"  
  # API_VERSION: "apigeeapi"
  DEFAULT_APIGEE_ORG: "bap-emea-apigee-5"
  DEFAULT_APIGEE_ENV: "default-dev"
  TEST_HOST: "34.117.38.184.nip.io"
  APIGEE_ORG: "bap-emea-apigee-5"
  APIGEE_ENV: "default-dev"

steps:

- label: "Generate SA key file"
  commands: 
    - pwd
    - echo "popo" > ./sa2.json
    - cat sa2.json
    - echo "___________________________________"
    - buildkite-agent artifact upload ./sa2.json

- label: "mvn deploy config xhybrid"
  commands: 
    - pwd
    - buildkite-agent artifact download sa2.json . 
    - buildkite-agent artifact download sa.json . --build $BUILDKITE_BUILD_ID
    - ls
    # if Linux Agent 
    # - sed -i '' "s/target_apigee_env/$APIGEE_ENV/g" ./EdgeConfig/edge.json
    # if Mac Agent 
    - sed -i".bck" "s/target_apigee_env/$APIGEE_ENV/g" ./EdgeConfig/edge.json
    - echo "___________________________________"
    - cat sa.json
    - echo "___________________________________"
    - mvn -X install -Pgoogleapi -Dapigee.org="bap-emea-apigee-5" -Denv="default-dev" -Dsa=sa.json -Dapigee.config.file=EdgeConfig/edge.json -Dapigee.config.options="update"