steps:

- label: "Define variables"
  commands: 
    - export API_VERSION="googleapi"  # or API_VERSION: apigeeapi
    - DEFAULT_APIGEE_ORG="bap-emea-apigee-5"
    - DEFAULT_APIGEE_ENV="default-dev"
    - TEST_HOST="34.117.38.184.nip.io"
    - APIGEE_ORG="bap-emea-apigee-5"
    - APIGEE_ENV="default-dev"

- label: "Generate SA key file"
  commands: 
    - pwd
    - echo "$GCP_SERVICE_ACCOUNT_TOKEN" > ./sa.json
    - ls 
    - buildkite-agent artifact upload ./sa.json

- label: "Generate SA key file"
  commands: 
    - pwd
    - buildkite-agent artifact download ./sa.json .
    - ls
    - sed -i '' "s/target_apigee_env/$APIGEE_ENV/g" ./EdgeConfig/edge.json
    - cat sa.json
    - mvn install -q -Pgoogleapi -Dapigee.org=$APIGEE_ORG -Denv=$APIGEE_ENV -Dsa=sa.json -Dapigee.config.file=./EdgeConfig/edge.json -Dapigee.config.options=update
